### PR TITLE
Adds a setting for debug logging (off by default)

### PR DESCRIPTION
**Pull request by chrisant996**
The debug logging was making it hard to see debug logging from other extensions.  This adds a setting, making it easy to turn on or off.

Resolves https://github.com/j0meinaster/bracket-peek/issues/7.

### CODE REVIEW

**Comment by chrisant996** [comment]
I've also now added a setting to put the peek on the closing line (immediately after the closing bracket or tag).

To differentiate in the Extensions pane between the original and my local version, I've also incremented the version number and changed the publisher Id.  _Sorry about that_ -- I don't know yet how to keep those kinds of changes private to my repo.

**Comment by j0meinaster** [comment]
Hey, 

Thanks for your effort. I will take a look tommorrow and see if it can be merged and released. 

Maybe it is a good Idea to make the hint position configurable (in line, at top of the Editor).

Can you please explain to me where you were able to See the logs? I only see them in the Extension host, when I test the extension, but I don't see the logs, when I install it from the store.

**Comment by chrisant996** [comment]
Hi, yes, I added a setting so it's configurable whether to show on the top line or on the closing line.  I also made it italics when it's on the closing line.  Maybe that should be a setting, too.

The logging output shows up in the Debug Console even when installed from the store, if the Debug Console is shown for any reason -- for example when I'm trying to develop extensions of my own.  :)  So I was getting a bunch of debug output from bracket-peek and it was making it very difficult to see my own logging output.  This is probably why so many extensions publish a configuration setting for a debugging mode.

**Comment by j0meinaster** [comment]
Thanks for the pull request and the great input, since I am new to extension development.

I moved the handling of enabling / logging to an environment parameter, which you can enter in the launch config, when starting / debugging the extensions. My reason was: I found it confusing for the user, to have a configuration in settings which will not affect anything, unless he's is the developer of this extension.

Thanks for pointing out the performance issue with the substring operations. I replaced the code with vsc internal functions.

I kept the italic settings, since it is a nice idea of customization. But it was not applied in 'preview on top' mode. So I fixed it.

I also kept the 'preview in line' mode, too. I have implemented it on my own initially, but it is not free of bugs. I think since it is configurable this option can stay. I moved the preview to end of line, since I don't like the behaviour of pushing the real code away while editing.
Also I found the following:
- The preview is not always displayed, when other in line code decorations are present e.g. gitlens. First comes, first serves :/
- When moving the cursor the preview is next to text and then jumps away to create a bigger offset. It feels buggy and I don't know how to control it
- The preview offset was not correct in markup languages e.g. html. I fixed it.
- The preview was not displayed when on the first line visible. I fixed it

As far ay I know, there can only be one publisher, so I added you as a contributor. Hope this is okay?

Since some things are still buggy I will not releas it yet.

I think about adding more configration options to make it more customizable. So anyone will find a configuration which suits best and does not colide with other extensions, like the nentioned gitlens:

preview modes:
- top
- end of line
- in line
- tooltip / hover

- disable preview on selection

- always show preview (even if opening lien is visible)

**Comment by chrisant996** [comment]
> Thanks for the pull request and the great input, since I am new to extension development.

I'm new as well -- thank you for the learning opportunity getting to read and modify this extension!

> I moved the handling of enabling / logging to an environment parameter, which you can enter in the launch config, when starting / debugging the extensions. My reason was: I found it confusing for the user, to have a configuration in settings which will not affect anything, unless he's is the developer of this extension.

Oh, I like that!  I didn't know such a thing was possible, so I had copied what lots of other extensions seem to be doing.  The environment parameter sounds much better.  :)

> I moved the preview to end of line, since I don't like the behaviour of pushing the real code away while editing.

Yes, I've encountered similar situations while editing the past couple days.  My idea didn't work out so well.  😆 

> * The preview is not always displayed, when other in line code decorations are present e.g. gitlens. First comes, first serves :/
> * When moving the cursor the preview is next to text and then jumps away to create a bigger offset. It feels buggy and I don't know how to control it

Yes, I've run into similar problems.  I wish VSCode had a way for extensions to show hovering messages.  I don't know a better solution, either.

> As far ay I know, there can only be one publisher, so I added you as a contributor. Hope this is okay?

Oh, certainly -- I had only changed the publisher name to make it easier for me to differentiate between the marketplace version and the .vsix file I installed.  I didn't mean to suggest I ought to be a publisher!

> Since some things are still buggy I will not release it yet.
> I think about adding more configration options to make it more customizable. ...

Understood.  Thanks for working on it, and brainstorming with me.

**Pull request merged**
